### ISSUE TITLE
No data found

### ISSUE THREAD

**Issue by TylerS1066** [APDevTeam/Beaming#9]
It appears that @TomLewis is having an interesting error message sent to a player when they beam.

See https://github.com/APDevTeam/Beaming/issues/6 for the error message.

@TomLewis, can you give me some more details on the specific paper build, EssentialsX version, Movecraft version, and Beaming version?  I've not see this bug on our production 1.12.2 paper server nor can I replicate it.

**Comment by TomLewis** [comment]
Sure! Thanks.

I was testing on my test server: `test.piratemc.com` so I can push changes/tests & you can all test yourselves too.

Current working setup:
```
Paper 1.12.2 (1617)
EssentialsX 2.18.1.0
Movecraft 7.0 Beta Eirikh 36 (https://github.com/eirikh1996/Movecraft/releases/tag/v7.0.0-for-1.8.8-1.16.4--beta-36)
```

It's been months since I tested and since I backdated to the working setup on my test box.

I think at the time, looking at changelogs I used:

1. https://github.com/eirikh1996/Movecraft/releases/tag/v7.0.0-for-1.8.8-1.16.5
2. Beaming hasn't been updated so its still https://github.com/APDevTeam/Beaming/releases/tag/2.a.0
3. Same essentials, same paper 1.12.2.

So the only change was that Movecraft via eirikh got updated since I last tested, Looks like Essentials is on a newer version too, is it a hard dependency?

**Comment by TylerS1066** [comment]
> 1. https://github.com/eirikh1996/Movecraft/releases/tag/v7.0.0-for-1.8.8-1.16.5
> 2. Beaming hasn't been updated so its still https://github.com/APDevTeam/Beaming/releases/tag/2.a.0
> 3. Same essentials, same paper 1.12.2.

Ah, I found an initial problem.  Beaming 2.a.0 is targeting Movecraft 8 and not 7.  For Movecraft 7, you will want to use v1.5.1: https://github.com/APDevTeam/Beaming/releases/tag/1.5.1.  Beaming does not officially support Eirik's fork, but I don't foresee any problems (I also won't be fixing any that arise tho).

If you are running 1.10.2-1.12.2, I *highly* recommend using [APDevTeam Movecraft 7.0.0](https://github.com/APDevTeam/Movecraft/releases/tag/7.0.0) since it is far better supported and stable than eirik's fork.  If you want to upgrade to 1.13+, I unfortunately do not have a good solution yet, but we are focusing on bringing Movecraft 8 (and the respective addon versions) to a stable state.




On our 1.12.2 paper server running Movecraft 7.0.0, Beaming 1.5.0, and EssentialsX 2.18.2 I do not see this error.  I'd recommend trying EssentialsX 2.18.2, Movecraft 7.0.0, and Beaming 1.5.1 (1.5.0 vs 1.5.1 was just an API version patch to support 1.13+, no affect on functionality) and seeing if the problem persists.  If it does, I suspect the problem is another plugin you have installed and not Beaming.

**Comment by TylerS1066** [comment]
Since there are no more comments, am I good to assume that switching to a supported version fixed the problem?

**Comment by TomLewis** [comment]
I just stayed on my old version as that works. This got put to the bottom of the priority list! 
So I've not tested it!
